### ISSUE TITLE
Update 2.66 Kurviger 1

### ISSUE THREAD

**Issue by ToToGSARider** [blackboxembedded/WunderLINQ-Android#148]
Hallo Keith, Kurviger 1 kann man ja noch aus dem Play Store laden wenn man es mal gekauft hat. Das sollte man mal auf alle Fälle noch aktiviert lassen.

Hi Keith, you can still download Kurviger 1 from the Play Store once you have purchased it. You should definitely leave it activated.

**Comment by ToToGSARider** [comment]
https://groups.google.com/a/blackboxembedded.com/g/wlq-users/c/bG2wzdxCPZ0

**Comment by blackboxembedded** [comment]
Ah, sorry I will add it back right away!

**Comment by blackboxembedded** [comment]
Resolved in 2.67. 6dc97f9a0b30d3cf8d845ec7fc2315179c020c14
