### ISSUE TITLE
WunderLINQ DFÜ

### ISSUE THREAD

**Issue by ToToGSARider** [blackboxembedded/WunderLINQ-Android#153]
Was ist neu in dem DFÜ Update 1.0.19 vom 21.01.2024

What is new in the DFÜ update 1.0.19 from 21.01.2024

**Comment by blackboxembedded** [comment]
Just cosmetic changes for clarity based on user feedback.

**Comment by ToToGSARider** [comment]
Okay, also muss ich ein Firmware Update machen an der WunderlinQ Hardware?

Okay, so I need to update the firmware on the WunderlinQ hardware?

**Comment by ToToGSARider** [comment]
Okay, also muss ich ein Firmware Update machen an der WunderlinQ Hardware?
Hallo Keith, muss man jede Firmware installieren, oder genügt die neuste? Sind in der höchsten Version alle anderen enthalten?


Okay, so I need to update the firmware on the WunderlinQ hardware?
Hi Keith, do you have to install every firmware or is the latest one sufficient? Does the highest version include all the others?

**Comment by blackboxembedded** [comment]
> Okay, also muss ich ein Firmware Update machen an der WunderlinQ Hardware?
> 
> Okay, so I need to update the firmware on the WunderlinQ hardware?

This was just an app update not a firmware update. 


> Okay, also muss ich ein Firmware Update machen an der WunderlinQ Hardware? Hallo Keith, muss man jede Firmware installieren, oder genügt die neuste? Sind in der höchsten Version alle anderen enthalten?
> 
> Okay, so I need to update the firmware on the WunderlinQ hardware? Hi Keith, do you have to install every firmware or is the latest one sufficient? Does the highest version include all the others?

They are independent from each other.

**Comment by ToToGSARider** [comment]
This was just an app update not a firmware update.

Wenn das nur ein Update für die DFÜ App war, wie wirkt sich das in der WunderLINQ App aus? DFÜ ist doch die Hardware? Es verbindet sich doch nur die WunderLINQ App mit dem Handy und die DFÜ wird doch nur für Firmware genommen, dachte ich. Kannst du das mal erklären?  

If this was just an update for the RDT app, what effect will it have on the WunderLINQ app? Isn't RDT the hardware? Only the WunderLINQ app connects to the cell phone and the DFÜ is only used for firmware, I thought. Can you explain that?

**Comment by blackboxembedded** [comment]
> Okay, ich habe gerade alle Updates auf der WunderLINQ Hardware von 1.9 bis 2.3 der Reihe nach installiert.
> 
> Okay, I have just installed all updates on the WunderLINQ hardware from 1.9 to 2.3 one after the other.

Sorry, I meant you only needed to install 2.3, sorry for the extra work. :)



> This was just an app update not a firmware update.
> 
> Wenn das nur ein Update für die DFÜ App war, wie wirkt sich das in der WunderLINQ App aus? DFÜ ist doch die Hardware? Es verbindet sich doch nur die WunderLINQ App mit dem Handy und die DFÜ wird doch nur für Firmware genommen, dachte ich. Kannst du das mal erklären?
> 
> If this was just an update for the DFÜ app, what effect will it have on the WunderLINQ app? Isn't DFÜ the hardware? Only the WunderLINQ app connects to the cell phone and the DFÜ is only used for firmware, I thought. Can you explain that?

The DFU app is only for applying firmware updates.  You are correct in your understanding. :)

**Comment by ToToGSARider** [comment]
> Sorry, I meant you only needed to install 2.3, sorry for the extra work. :)

Alles Okay, ich habe das ja schon gemacht, bevor du geantwortet hast. Dann weiss ich aber für das 2-Gerät Bescheid. Aber es ist ja meistens sowieso besser, wenn man Updates Schritt für Schritt macht.

Everything's okay, I already did that before you replied. But then I know about the 2 device. But it's usually better to do updates step by step anyway.

**Comment by ToToGSARider** [comment]
Hello @blackboxembedded ,

gibt es schon eine neue DFÜ Version für das WunderLINQ? Bei welcher Version sind wir aktuell? 

Hello @blackboxembedded ,

Is there already a new DFÜ version for the WunderLINQ? Which version are we currently on?

**Comment by blackboxembedded** [comment]
There is no new firmware. The current version is 2.3.
