### ISSUE TITLE
Automatic start of WunderLINQ app fails / Automatischer Start WunderLINQ App scheitert

### ISSUE THREAD

**Issue by ToToGSARider** [blackboxembedded/WunderLINQ-Android#169]
The automatic start of the WunderLINQ app no longer works for me. I have allowed everything in the permissions. 

Bei mir funktioniert der automatische Start der WunderLINQ App nicht mehr. Ich habe in den Berechtigungen alles erlaubt. 
Handy: Samsung S20+ mit Android 13 und One UI-Version 5.1
App Version: 2.76 Firmware 2.3

**Comment by blackboxembedded** [comment]
I'll see if I can confirm on my S23 test device.

**Comment by blackboxembedded** [comment]
@ToToGSARider My S23 test device on the latest firmware is OneUI 6.1, when the auto launch is enabled in the app it did work for me.  This process to auto-launch can be hot or miss on some devices, however fundamentally it looks like it is working.

**Comment by ToToGSARider** [comment]
Okay, ich werde die App mal deinstallieren und neu installieren und schauen, ob es dann wieder funktioniert. 

Okay, I'll uninstall and reinstall the app and see if it works again.

**Comment by ToToGSARider** [comment]
Hi Keith, reinstalling the app fixed the problem.
