### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by hickenjr** [blackboxembedded/WunderLINQ-Android#171]
Not sure if these options can be added.
I use a 10 in Android tablet and love it but the size does cover the top part of the 2014 R1200GS dash. 
It would be nice if:
1. There was an indicator that cruise control is enabled.
2. Turn signal is on indicator(Left/Right arrow)

Not a big deal either way. I typically run WL in split screen and the way the TFT scales there is a lot af screen real estate to work with. 
Perhaps even a "Split Screen" mode that places the RPM/Speed/Gear on the top half and the informational stuff in the bottom half.

Just some thoughts.
Thanks
![03 07 2024_13 36 40_REC](https://github.com/blackboxembedded/WunderLINQ-Android/assets/174652919/b0923b9c-019c-408f-b5f6-640b73763c7b)

**Comment by blackboxembedded** [comment]
Unfortunately, cruise control and signal light status data points aren't available through the Nav Cradle.
