### ISSUE TITLE
Sport Dashboard for WunderLINQ App

### ISSUE THREAD

**Issue by ToToGSARider** [blackboxembedded/WunderLINQ-Android#182]
Hallo Keith,

ist es technisch möglich, dass ihr auch noch das Sport Dashboard für die WunderLINQ App bauen könntet? Es gibt GS Fahrer, die fänden das echt cool, wenn sie Alternativ noch die Schräglage beim fahren sehen könnten wie bei den neuen 1300er Modellen.  

Hello Keith,

is it technically possible that you could also build the Sport Dashboard for the WunderLINQ app? There are GS riders who would find it really cool if they could alternatively see the lean angle while riding like on the new 1300 models.

**Comment by blackboxembedded** [comment]
Hi,

We have Sport and Adventure dashboards as well. You can long-press the screen or use the long-press right on the wheel to toggle through them.
