### ISSUE TITLE
Changing value in data grid customization popup does not update screen value in app settings list

### ISSUE THREAD

**Issue by motomatters** [blackboxembedded/WunderLINQ-Android#98]
When customizing the data grid to display the values you want to see on the app setting page, the list of selected values does not update after selecting a different value. The value displayed in the data grid is changed correctly, and if you exit app settings and then select Data Grid Customization, the correct, updated list is displayed.

To reproduce:
1. In App Settings, select Data Grid Customization
2. Select one of the values between First and Fifteenth you wish to alter 
3. Change the preset value (e.g. from Fuel Range to RPM, etc)
4. In the list of values, the value is unchanged, until you exit the App Settings screen

How it should work:
1. In App Settings, select Data Grid Customization
2. Select one of the values between First and Fifteenth you wish to alter 
3. Change the preset value (e.g. from Fuel Range to RPM, etc)
4. The new value just selected is displayed

As noted above, the Data Grid is correctly altered. But it looks like the screen on the App Settings page is not refreshed when a value is changed.

Tested with Android 9 and Android 12

**Comment by blackboxembedded** [comment]
Fixed 4f3695c3085394cfd179525a1c2bf98f50d913ac
